
create table bank_accounts (
        id bigint generated by default as identity,
        account_holder_name varchar(255),
        account_number varchar(255),
        account_type varchar(255),
        balance_amt numeric(38,2),
        created_date timestamp(6),
        primary key (id)
    )


CREATE TABLE atm_transactions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    transaction_date timestamp(6) NOT NULL,
    transaction_amt double precision NOT NULL,
    trnsaction_type varchar(255) NOT NULL,
    bankaccount_id bigint NOT NULL,
    CONSTRAINT atm_transactions_pkey PRIMARY KEY (id),
    CONSTRAINT fkatmbank FOREIGN KEY (bankaccount_id)
        REFERENCES bank_accounts (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

